### PR TITLE
Display only links to active categories inside articles

### PR DESCRIPTION
**Pull request by query-string**
This PR fixes issue [#2312](https://github.com/saberespoder/inboundsms/issues/2312)

UPD: since @skatkov has recently requested this bug to be tested, this PR now contains RSpec setup and a basic test suite that covers not only the bug in question but also some key components functionality.

### CODE REVIEW

**Review by FanaHOVA — APPROVED** [review]
I'm getting scared by all these methods being appended, we should start writing some specs soon 😛  Good for now though, let's launch this thing!

**Review by skatkov — CHANGES_REQUESTED** [review]
If it's a bug, it needs a spec. Please add one!

**Comment by query-string** [comment]
@skatkov specs added ;)

**Review by skatkov — APPROVED** [review]
We need to speak about big pull requests and integration tests :P but other then that, looks good. didn't notice any big issues.

**Pull request merged**
